# Generated by Django 5.0.3 on 2024-03-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Book_Author',
        ),
        migrations.RenameModel(
            old_name='Publisher',
            new_name='Book_Publisher',
        ),
        migrations.RenameModel(
            old_name='Branch',
            new_name='Library_Branch',
        ),
    ]
