# Generated by Django 5.0.3 on 2024-03-18 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_author_book_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='book',
            name='num_copies',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_year',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(1990)]),
        ),
        migrations.AddField(
            model_name='book_publisher',
            name='pubilsher_address',
            field=models.CharField(default='Unknown', max_length=60),
        ),
        migrations.AddField(
            model_name='book_publisher',
            name='publisher_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(6000000000)]),
        ),
        migrations.AddField(
            model_name='borrower',
            name='borrower_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(6000000000)]),
        ),
        migrations.AlterField(
            model_name='book_author',
            name='author_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='book_publisher',
            name='publisher_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='borrower_name',
            field=models.CharField(max_length=30),
        ),
    ]
