# Generated by Django 5.0.3 on 2024-03-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_borrower_contact_info_book_num_copies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library_branch',
            name='branch_name',
            field=models.CharField(max_length=60),
        ),
    ]
