# Generated by Django 5.0.3 on 2024-03-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_library_branch_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_publisher',
            name='pubilsher_address',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
