# Generated by Django 5.0.3 on 2024-03-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_book_publisher_pubilsher_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_publisher',
            name='pubilsher_address',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
