# Generated by Django 5.0.3 on 2024-03-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_book_publisher_pubilsher_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher_year',
            new_name='published_year',
        ),
    ]
