# Generated by Django 5.0.3 on 2024-03-21 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_publisher_year_book_published_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(1950)]),
        ),
    ]
